### ISSUE TITLE
Not working when daemonized on macOS Big Sur

### ISSUE THREAD

**Issue by virtualxdriver** [zizi4n5/homebridge-switchbot-for-mac#23]
Similar to https://github.com/abandonware/noble/issues/143#issue-742284775

The plugin is unable to communicate with SwitchBot devices when run as a daemon (via `hb-service`).

    [11/20/2020, 11:54:48 AM] [Bot] Failed to discover WoHand (C0:51:13:D6:C2:9C). Is Bluetooth enabled?
    [11/20/2020, 11:54:48 AM] [Bot] Error: Failed to initialize the Noble object: resetting
        at Noble.<anonymous> (/opt/homebrew/lib/node_modules/homebridge-switchbot-for-mac/node_modules/node-switchbot/lib/switchbot.js:171:25)
        at Object.onceWrapper (node:events:436:26)
        at Noble.emit (node:events:341:22)
        at Noble.onStateChange (/opt/homebrew/lib/node_modules/homebridge-switchbot-for-mac/node_modules/@abandonware/noble/lib/noble.js:87:8)
        at NobleMac.emit (node:events:329:20)

The plugin is able to communicate with SwitchBot devices when run directly in a terminal with `sudo homebridge` (at which point the user gets prompted to grant Bluetooth access to the Terminal app).

**Comment by virtualxdriver** [comment]
Figured it out. I had to manually grant Bluetooth access in Settings > Privacy to the node executable, then restart the homebridge service with `sudo hb-service restart`.

**Comment by virtualxdriver** [comment]
Never mind, I can't get it to work reliably after a reboot.

**Comment by zizi4n5** [comment]
@virtualxdriver 
Thank you.
I didn't know how to deal with the problem that doesn't work in Big Sur, so this Issue is very good information and helpful.
I will include this information in the README.

**Comment by zizi4n5** [comment]
> I will include this information in the README.

Added the following.
https://github.com/zizi4n5/homebridge-switchbot-for-mac#big-sur

**Comment by virtualxdriver** [comment]
Awesome, thanks a lot for the support! Keep up the good work, this plugin is great! :)
